/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:87f050e0-b452-44ab-8fd7-5610cd3b9484",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QXh6SQirW",
    "aws_user_pools_web_client_id": "2d7qbclp94mkecj3e8mbjgfvch",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://a2zbuiz6xrbptd4yloumlayf6y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5vrsyyxojjftda3xva3jaryi74",
    "aws_user_files_s3_bucket": "scrambl32545-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
